export default{
    PRIMARY_COLOR: '#003844',
    PRIMARY_COLOR_DARK: '#000000',
    PRIMARY_COLOR_TEXT: '#006c67',
    PRIMARY_BORDER_COLOR: '#ffb100',
    SECONDARY_COLOR_TEXT: '#ffebc6',
    SECONDARY_COLOR: '#FEEFDD',
    BUTTON_TEXT_COLOR: '#50b2c0',
    TRANSPARENT: 'rgba(0,0,0,0)'
}